In [1]:
import pandas as pd 
import numpy as np

clients = ['AA','AM', 'BT', 'VOL', 'VIVA']
ac = ['A319', 'A320', 'A321','737']
station = ['ACA', 'BJX', 'CZM','DGO','GDL']
svc = ['A','B','C','D','E']
index = pd.MultiIndex.from_product([clients, ac])
print(index)
columns = pd.MultiIndex.from_product([station,svc])
content = [i for i in range(len(index)+len(columns))]
tuples = list(zip(index,columns))
print(tuples)
df = pd.DataFrame( index=index, columns=columns)
df.index.names = ['Client','AC']
df.columns.names = ['Station', 'Service']

# Generate random data with the shape of the MultiIndex
random_data = np.random.rand(len(index), len(columns))

# Assign the random data to the DataFrame
df = pd.DataFrame(random_data, index=index, columns=columns)

print(df)


df.fillna(1, inplace=True)
df.to_excel('File-Bogar.xlsx')
df

ModuleNotFoundError: No module named 'pandas'

In [145]:
df = df.stack(1).stack()
df

Client  AC    Service  Station
AA      A319  A        ACA        0.384591
                       BJX        0.606577
                       CZM        0.734845
                       DGO        0.691576
                       GDL        0.703006
                                    ...
VIVA    737   E        ACA        0.564672
                       BJX        0.530068
                       CZM        0.585364
                       DGO        0.422024
                       GDL        0.401054
Length: 500, dtype: float64

In [146]:
df.name = 'Data'
df = df.unstack()
df

Station                   ACA       BJX       CZM       DGO       GDL
Client AC   Service
AA     737  A        0.979730  0.215107  0.764780  0.904343  0.972543
            B        0.691203  0.058974  0.266388  0.097139  0.985474
            C        0.358301  0.451966  0.470535  0.200749  0.615642
            D        0.021490  0.270093  0.842604  0.335693  0.905173
            E        0.206670  0.843948  0.225412  0.536241  0.874944
...                       ...       ...       ...       ...       ...
VOL    A321 A        0.774724  0.307972  0.921551  0.830807  0.104725
            B        0.688544  0.423590  0.058472  0.551221  0.743003
            C        0.022658  0.789257  0.871478  0.590422  0.065157
            D        0.875223  0.995263  0.270720  0.161959  0.735246
            E        0.972552  0.823132  0.178846  0.254190  0.960439

[100 rows x 5 columns]

In [147]:
#df.pivot(index=['Client','AC'],columns='Station',values='Data')
pivot_df = df.pivot_table(index=['Client', 'AC'], columns='Station', values='Data')

KeyError: 'Data'

In [91]:

am = df.xs('AM', axis=0, level='Client')
print(am)
aca = am.xs('ACA', axis=1, level='Station')
aca

Station       ACA                                               BJX            \
Service         A         B         C         D         E         A         B
AC
A319     0.502783  0.915452  0.792416  0.162138  0.224640  0.667859  0.534384
A320     0.061516  0.518266  0.011747  0.240750  0.762463  0.583336  0.072756
A321     0.698106  0.849163  0.753373  0.510781  0.977625  0.262827  0.977574
737      0.832792  0.228473  0.866540  0.355377  0.424295  0.645864  0.725511

Station                                ...       DGO                      \
Service         C         D         E  ...         A         B         C
AC                                     ...
A319     0.992536  0.428880  0.914221  ...  0.649092  0.213489  0.482697
A320     0.266508  0.176109  0.197477  ...  0.833436  0.600375  0.663811
A321     0.633864  0.680355  0.876171  ...  0.482179  0.217874  0.398633
737      0.772337  0.983492  0.032491  ...  0.091969  0.727793  0.800005

Station                           GDL
Service         D         E         A         B         C         D         E
AC
A319     0.829687  0.995235  0.481916  0.588606  0.907323  0.806468  0.630241
A320     0.451048  0.704022  0.024540  0.796913  0.387394  0.931646  0.514187
A321     0.603285  0.507110  0.418380  0.985229  0.569227  0.335223  0.210754
737      0.422984  0.452780  0.280358  0.741188  0.112188  0.006239  0.125944

[4 rows x 25 columns]

Service         A         B         C         D         E
AC
A319     0.502783  0.915452  0.792416  0.162138  0.224640
A320     0.061516  0.518266  0.011747  0.240750  0.762463
A321     0.698106  0.849163  0.753373  0.510781  0.977625
737      0.832792  0.228473  0.866540  0.355377  0.424295

In [92]:
df.loc['AM']

Station       ACA                                               BJX            \
Service         A         B         C         D         E         A         B
AC
A319     0.502783  0.915452  0.792416  0.162138  0.224640  0.667859  0.534384
A320     0.061516  0.518266  0.011747  0.240750  0.762463  0.583336  0.072756
A321     0.698106  0.849163  0.753373  0.510781  0.977625  0.262827  0.977574
737      0.832792  0.228473  0.866540  0.355377  0.424295  0.645864  0.725511

Station                                ...       DGO                      \
Service         C         D         E  ...         A         B         C
AC                                     ...
A319     0.992536  0.428880  0.914221  ...  0.649092  0.213489  0.482697
A320     0.266508  0.176109  0.197477  ...  0.833436  0.600375  0.663811
A321     0.633864  0.680355  0.876171  ...  0.482179  0.217874  0.398633
737      0.772337  0.983492  0.032491  ...  0.091969  0.727793  0.800005

Station                           GDL
Service         D         E         A         B         C         D         E
AC
A319     0.829687  0.995235  0.481916  0.588606  0.907323  0.806468  0.630241
A320     0.451048  0.704022  0.024540  0.796913  0.387394  0.931646  0.514187
A321     0.603285  0.507110  0.418380  0.985229  0.569227  0.335223  0.210754
737      0.422984  0.452780  0.280358  0.741188  0.112188  0.006239  0.125944

[4 rows x 25 columns]

In [183]:
csdf = pd.read_excel('Cust Serv Sum STD.xls')

In [184]:
csdf.fillna('', inplace=True)

In [191]:
print(type(csdf.loc[1,'CUN']))
csdf.loc[1,'CUN']

<class 'str'>

'[A340,     A330]'

In [186]:
csdf.head(24)

,Unnamed: 0,Unnamed: 1,ACA,AGU,BJX,CTM,CUL,CUN,CUU,CZM,...,ZIH,ZLO,Unnamed: 34,Unnamed: 35,Unnamed: 36,LOG-BOOK ENTRIES AND AIRCRAFT RELEASE,Unnamed: 38,PFC,Unnamed: 40,Unnamed: 41
0,1,21 Air,,,,,,,,,...,,,,"Routine service all Transits, RON IN & OUT. M...",,FAA A&P Certificate.,,,,Follow 21 Air Policies and Procedures. Oil & ...
1,2,AerolÃ­neas Argentinas,,,,,,"[A340, A330]",,,...,,,,"Routine Transits, RON IN & OUT, headsets arr &...",,Follow AR instructions to comply with the auth...,,,,Follow AR policies and procedures to comply wi...
2,3,AerouniÃ³n,,,,,,,,,...,,,,"Technical assistance to every transit, RON IN ...",,N/A Technical assistnace only. NO certificat...,,,,Follow AerouniÃ³n on-board technician instructi...
3,4,Air Canada,,,,,,A220 A319 A320 A321 A330 737 767 777 787,,A319 A320 A321 737,...,A220 A319 A320 A321 737 767,,,"Routine service Transits, RON IN & OUT, servic...",,TCCA certification under Air Canada authority....,,,,For log-book entries and releases use the Air ...
4,5,Air CaraÃ¯bes,,,,,,A330 A350,,,...,,,,"Routine service Transits, RON IN & OUT, head-s...",,A&PIS EASA Part 145 certification,,âˆš,,Follow Air Caraibes / Air France + A&PIS EASA ...
5,6,Air Europa,,,,,,A330 787,,NO OP,...,,,,"Routine service Transits, RON IN & OUT, meet w...",,A&PIS EASA Part 145 certification,,âˆš,,Follow Air Europa procedures in accordance wit...
6,7,Air France,,,,,,A330 A350 777 787,,,...,,,,"Routine service Transits, RON IN & OUT, head-s...",,A&PIS EASA Part 145 certification,,âˆš,,Follow Air France + A&PIS EASA MOE policies an...
7,8,Air Tanker,,,,,,A330,,,...,,,,"Routine service Transits, RON IN & OUT, meet, ...",,A&PIS EASA Part 145 certification,,âˆš,,Follow Air Tanker procedures & A&PIS EASA MOE ...
8,9,Air Transat,A320 A321,,,,,,,A320 A321,...,A320 A321,,,"Routine service Transits, RON IN & OUT, meet a...",,TCCA certification under Air Transat authority.,,,,Follow Air Transat procedures and also instruc...
9,10,Alaska Airlines,NO OP,,,,,A320 A321 737,,,...,A320 A321 737,A320 A321 737,,"Routine service Transits, RON IN & OUT, mainte...",,FAA A&P certificate,,,,Contact Alaska maintenance control for all wor...
10,11,Allegiant Air,,,,,,A319 A320,,,...,,,,"Routine service Transits, RON IN & OUT, mainte...",,FAA A&P certificate.,,,,Follow Allegiant Air line maintenance procedures.
11,12,All Nippon Airways,,,,,,,,,...,,,,"Routine Transits, RON IN & OUT, meet upon arri...",,A&PIS in accordance with JCAB certification,,âˆš,,Follow strictly ANA's procedures and comply wi...
12,13,American Airlines,,A319 A320 A321,A319 A320 A321 737,,,,,A319 A320 A321 737,...,A319 A320 A321 737,,,"Routine servce all Transits, RON IN & RON OUT,...",,FAA A&P certificate. Print WO for each servic...,,,,"Meet&greet, fueling assis, servicing + maint a..."
13,14,Arke TUI NL,,,,,,767 787,,,...,,,,"Routine service Transits, RON IN & OUT, meet, ...",,A&PIS EASA Part 145 certification,,âˆš,,Folllow Arkefly instructions on its line maint...
14,15,Atlas Air,,,,,,,,,...,,,,"Routine service Transits, RON IN & OUT; head-s...",,FAA A&P certificate,,,,Follow Atlas Air procedures. No plans to oper...
15,16,Austrian,,,,,,767 777,,,...,,,,"Routine service Transits, RON IN & OUT, head-s...",,A&PIS EASA Part 145 certification,,âˆš,,Folllow Austrian instructions and procedures.
16,17,Azur Air (Ukraine),,,,,,767 777,,,...,,,,"Routine service Transits, RON IN & RON OUT, he...",,Use one-time-release authorization from Azur A...,,,,Follow Azur Air (Ukraine) procedures and A&PIS...
17,18,British Airways,,,,,,777,,,...,,,,"Routine service Transits, RON IN & OUT, head s...",,A&PIS UK CAA certification,,âˆš,,Follow BA procedures and notifications as inst...
18,19,Canadian North,,,,,,737,,NO OP,...,,,,"Routine service to all transits, RON IN & RON ...",,Canadian North on-board technician certifies a...,,,,Follow CN on-board technician instructions unt...
19,20,Cargo Airlines,,,,,,,,,...,,,,"Routine service Transits, RON IN & OUT, meet, ...",,A&PIS Israel certification,,,,Assign one certifying engineer for three conse...
20,21,Cargojet,,,,,,,,,...,,,,"Routine service all Transits, RON IN & OUT. M...",,Cargojet authorization in accordance with TCCA.,,,,Follow Cargojet policies and procedures. Oil ...
21,22,Cargolux,,,,,,,,,...,,,,"Routine service Transits, RON IN & OUT, head s...",,A&PIS EASA Part 145 certification,,,,Follow Cargolux procedures. Contract includes...
22,23,Cathay Pacific,,,,,,,,,...,,,,"Routine Transits, RON IN & OUT, head sets arr&...",,A&PIS Hong Kong (China) authority procedures i...,,,,Follow Cathay Pacific procedures. Complete al...
23,24,China Southern,,,,,,,,,...,,,,"Routine Transits, RON IN & OUT, head sets arr&...",,AFAC licence number or authorization number is...,,âˆš,,Follow China Southern policies and procedures

In [193]:
clients = ['A21','AA','BA']
ac = [["A320","A321","767"],["A320", "787"],[]]
df1 = pd.DataFrame({"Clients": clients, "ACA":ac})
# add station
df1['BJX'] = [["A320","A321","767"],["A320", "787"],["A321"]]
# add services
df1['Services'] = [["A","B","C"],["A", "B"],["C"]]
# Step 1: Set "keys" as the index
df1.set_index('Clients', inplace=True)
print(df1)
df1.to_excel('df1.xlsx')

                       ACA                BJX   Services
Clients
A21      [A320, A321, 767]  [A320, A321, 767]  [A, B, C]
AA             [A320, 787]        [A320, 787]     [A, B]
BA                      []             [A321]        [C]

In [174]:
# Access AC values for the client "AA"
aa_ac_values = df1.loc['AA', 'ACA']
print(aa_ac_values)

['A320', '787']

In [177]:
# Iterate over the elements of the "A21" row under the "ACA" column
for element in df1.loc['A21', 'ACA']:
    print(element)

A320
A321
767

In [178]:
# List comprehension to iterate over the elements of the "A21" row under the "ACA" column
elements_a21_aca = [element for element in df1.loc['A21', 'ACA']]
print(elements_a21_aca)

['A320', 'A321', '767']